@startuml
'https://plantuml.com/class-diagram
namespace nav2_core{
class Controller{
-- public method --
using Ptr = std::shared_ptr<nav2_core::Controller>;
virtual ~Controller()
virtual void configure(LifecycleNode&,name,tf2_ros::Buffer&,Costmap2DROS&) = 0;
virtual void cleanup() = 0;
virtual void activate() = 0;
virtual void deactivate() = 0;
virtual void setPlan(const nav_msgs::msg::Path & path) = 0;
virtual TwistStamped computeVelocityCommands(pose,velocity) = 0;
}
}

namespace dwb_msgs{
class CriticScore
class LocalPlanEvaluation
class Trajectory2D
class TrajectoryScore

class DebugLocalPlan
class GenerateTrajectory
class GenerateTwists
class GetCriticScore
class ScoreTrajectory
}

namespace nav_2d_msgs{
class Path2D
class Pose2D32
class Pose2dStamped
class Twist2D
class Twist2D32
class Twist2DStamped
}

namespace nav_2d_utils{
class conversion{
geometry_msgs::msg::Twist twist2Dto3D(const nav_2d_msgs::msg::Twist2D & cmd_vel_2d);
nav_2d_msgs::msg::Twist2D twist3Dto2D(const geometry_msgs::msg::Twist & cmd_vel);
nav_2d_msgs::msg::Pose2DStamped poseStampedToPose2D(const geometry_msgs::msg::PoseStamped & pose);
geometry_msgs::msg::Pose2D poseToPose2D(const geometry_msgs::msg::Pose & pose);
geometry_msgs::msg::Pose pose2DToPose(const geometry_msgs::msg::Pose2D & pose2d);
geometry_msgs::msg::PoseStamped pose2DToPoseStamped(const nav_2d_msgs::msg::Pose2DStamped & pose2d);
geometry_msgs::msg::PoseStamped pose2DToPoseStamped(pose2d,frame, stamp);
nav_msgs::msg::Path posesToPath(const std::vector<geometry_msgs::msg::PoseStamped> & poses);
nav_2d_msgs::msg::Path2D pathToPath2D(const nav_msgs::msg::Path & path);
nav_msgs::msg::Path poses2DToPath(poses,frame, stamp);
nav_msgs::msg::Path pathToPath(const nav_2d_msgs::msg::Path2D & path2d);
}
class OdomSubscriber{
-- public method --
explicit OdomSubscriber(nh,default_topic = "odom")
inline nav_2d_msgs::msg::Twist2D getTwist()
inline nav_2d_msgs::msg::Twist2DStamped getTwistStamped()
--protected method --
void odomCallback(const nav_msgs::msg::Odometry::SharedPtr msg)
-- protected data --
rclcpp::Subscription<Odometry>::SharedPtr odom_sub_;
nav_2d_msgs::msg::Twist2DStamped odom_vel_;
std::mutex odom_mutex_;
}
class parameters{
param_t<?type> searchAndGetParam(nh,param_name, default_value)
param_t<?type> loadParameterWithDeprecation(nh,current_name,old_name,default_value)
void moveDeprecatedParameter(nh,current_name,old_name)
void moveParameter(nh,old_name,current_name,default_value,should_delete)
}
class path_ops{
Path2D adjustPlanResolution(global_plan_in,resolution)
}
class tf_helper{
bool transformPose(tf,frame,in_pose,out_pose,transform_tolerance);
}
}


namespace costmap_queue{

class MapBaseQueue<? item_t>{
explicit MapBasedQueue(bool reset_bins = true)
virtual void reset()
void enqueue(const double priority, item_t item)
bool isEmpty()
item_t & front()
void pop()

-- protected data --
using ItemMap = std::map<double, std::vector<item_t>>;
using ItemMapIterator = typename ItemMap::iterator;
bool reset_bins_;
ItemMap item_bins_;
unsigned int item_count_;
ItemMapIterator iter_;
ItemMapIterator last_insert_iter_;
}

class CellData{
-- public method --
CellData(d, i, x, y, sx, sy)
CellData()
static unsigned absolute_difference(x, y)

-- public data --
double distance_;
unsigned int index_;
unsigned int x_, y_;
unsigned int src_x_, src_y_;
}

class CostmapQueue{
-- public method --
explicit CostmapQueue(costmap, manhattan);
void reset() override;
void enqueueCell(unsigned int x, unsigned int y);
CellData getNextCell();
virtual bool validCellToQueue(const CellData & /*cell*/)
-- public data --
typedef std::shared_ptr<CostmapQueue> Ptr;
-- protected method --
void enqueueCell(index,cur_x,cur_y,src_x,src_y);
void computeCache();
inline double distanceLookup(cur_x,cur_y,src_x,src_y)

-- protected data --
nav2_costmap_2d::Costmap2D & costmap_;
std::vector<bool> seen_;
int max_distance_;
bool manhattan_;
std::vector<std::vector<double>> cached_distances_;
int cached_max_distance_;
}

class LimitedCostmapQueue{
-- public method --
LimitedCostmapQueue(costmap, cell_distance_limit);
bool validCellToQueue(const CellData & cell) override;
}


MapBaseQueue <-- CostmapQueue
CostmapQueue o-- CellData
CostmapQueue *-- Costmap2D
CostmapQueue <-- LimitedCostmapQueue
}


namespace dwb_plugins{
class KinematicParameters
{
-- public method --
friend class KinematicsHandler;
inline double getMinX()
inline double getMaxX()
inline double getAccX()
inline double getDecelX()
inline double getMinY()
inline double getMaxY()
inline double getAccY()
inline double getDecelY()
inline double getMinSpeedXY()
inline double getMaxSpeedXY()
inline double getMinTheta()
inline double getMaxTheta()
inline double getAccTheta()
inline double getDecelTheta()
inline double getMinSpeedTheta()
inline double getMinSpeedXY_SQ()
inline double getMaxSpeedXY_SQ()
-- protected data --
double min_vel_x_;
double min_vel_y_;
double max_vel_x_;
double max_vel_y_;
double max_vel_theta_;
double min_speed_xy_;
double max_speed_xy_;
double min_speed_theta_;
double acc_lim_x_;
double acc_lim_y_;
double acc_lim_theta_;
double decel_lim_x_;
double decel_lim_y_;
double decel_lim_theta_;
double min_speed_xy_sq_;
double max_speed_xy_sq_;
}

class KinematicsHandler
{
-- public method --
KinematicsHandler();
~KinematicsHandler();
void initialize(nh, plugin_name);
inline KinematicParameters getKinematics()
using Ptr = std::shared_ptr<KinematicsHandler>;
-- protected method --
void on_parameter_event_callback(const rcl_interfaces::msg::ParameterEvent::SharedPtr event);
void update_kinematics(KinematicParameters kinematics);
-- protected data --
std::atomic<KinematicParameters *> kinematics_;
rclcpp::AsyncParametersClient::SharedPtr parameters_client_;
rclcpp::Subscription<ParameterEvent>::SharedPtr parameter_event_sub_;
std::string plugin_name_;
}

class OneDVelocityIterator{
-- public method --
inline double projectVelocity(v0, accel, decel, dt, target)
OneDVelocityIterator(current,min,max,acc_limit,decel_limit,acc_time,num_samples)
double getVelocity() const
void reset()
bool isFinished() const
OneDVelocityIterator & operator++()
-- private data --
bool return_zero_, return_zero_now_;
double min_vel_, max_vel_;
double current_;
double increment_;
}

class VelocityIterator{
-- public method --
virtual ~VelocityIterator()
virtual void initialize(nh, kinematics,plugin_name) = 0;
virtual void startNewIteration(current_velocity, dt) = 0;
virtual bool hasMoreTwists() = 0;
virtual nav_2d_msgs::msg::Twist2D nextTwist() = 0;
}

class XYThetaIterator{
-- public method --
XYThetaIterator()
void initialize(nh,kinematics,plugin_name) override;
void startNewIteration(current_velocity,dt) override;
bool hasMoreTwists() override;
nav_2d_msgs::msg::Twist2D nextTwist() override;
-- protected method --
bool isValidSpeed(double x, double y, double theta);
virtual bool isValidVelocity();
void iterateToValidVelocity();
-- protected data --
int vx_samples_, vy_samples_, vtheta_samples_;
KinematicsHandler::Ptr kinematics_handler_;
std::shared_ptr<OneDVelocityIterator> x_it_, y_it_, th_it_;
}

class StandardTrajectoryGenerator{
-- public method --
void initialize(nh,plugin_name) override;
void startNewIteration(current_velocity) override;
bool hasMoreTwists() override;
nav_2d_msgs::msg::Twist2D nextTwist() override;
Trajectory2D generateTrajectory(start_pose,start_vel,cmd_vel) override;
-- protected method --
virtual void initializeIterator(const nav2_util::LifecycleNode::SharedPtr & nh);
virtual Twist2D computeNewVelocity(cmd_vel, start_vel,dt);
virtual geometry_msgs::msg::Pose2D computeNewPosition(start_pose, vel, dt);
virtual std::vector<double> getTimeSteps(const nav_2d_msgs::msg::Twist2D & cmd_vel);
-- protected data --
KinematicsHandler::Ptr kinematics_handler_;
std::shared_ptr<VelocityIterator> velocity_iterator_;
double sim_time_;
bool discretize_by_time_;
double time_granularity_;
double linear_granularity_;
double angular_granularity_;
std::string plugin_name_;
bool include_last_point_;
}
class LimitedAccelGenerator{
-- public method --
void initialize(nh,plugin_name) override;
void startNewIteration(current_velocity) override;

-- protected method --
Twist2D computeNewVelocity(cmd_vel,start_vel,dt) override;

-- protected data --
double acceleration_time_;
std::string plugin_name_;

}

KinematicsHandler *-- KinematicParameters
VelocityIterator <-- XYThetaIterator
XYThetaIterator *-- KinematicsHandler
XYThetaIterator *-- OneDVelocityIterator
StandardTrajectoryGenerator *-- KinematicsHandler
StandardTrajectoryGenerator *-- VelocityIterator
StandardTrajectoryGenerator <-- LimitedAccelGenerator
}




namespace dwb_core{
class DWBLocalPlanner{
-- public method --
DWBLocalPlanner();
void configure(node,tf,costmap_ros) override;
virtual ~DWBLocalPlanner() {}
void activate() override;
void deactivate() override;
void cleanup() override;
void setPlan(path) override;
TwistStamped computeVelocityCommands(pose,velocity) override;
virtual TrajectoryScore scoreTrajectory(traj,best_score = -1);
virtual Twist2DStamped computeVelocityCommands(pose,velocity,results);
-- protected method --
void prepareGlobalPlan(pose,transformed_plan,goal_pose,publish_plan);
virtual TrajectoryScore coreScoringAlgorithm(pose,velocity,results);
virtual Path2D transformGlobalPlan(pose);
std::string resolveCriticClassName(std::string base_name);
virtual void loadCritics();
void loadBackwardsCompatibleParameters();
-- protected data --
nav_2d_msgs::msg::Path2D global_plan_;
bool prune_plan_;
double prune_distance_;
bool debug_trajectory_details_;
rclcpp::Duration transform_tolerance_{0, 0};
bool shorten_transformed_plan_;
rclcpp_lifecycle::LifecycleNode::SharedPtr node_;
std::shared_ptr<tf2_ros::Buffer> tf_;
std::shared_ptr<nav2_costmap_2d::Costmap2DROS> costmap_ros_;
std::unique_ptr<DWBPublisher> pub_;
std::vector<std::string> default_critic_namespaces_;
pluginlib::ClassLoader<TrajectoryGenerator> traj_gen_loader_;
TrajectoryGenerator::Ptr traj_generator_;
pluginlib::ClassLoader<TrajectoryCritic> critic_loader_;
std::vector<TrajectoryCritic::Ptr> critics_;
std::string dwb_plugin_name_;
bool short_circuit_trajectory_evaluation_;
}

class IllegalTrajectoryTracker{
-- public method --
IllegalTrajectoryTracker()
void addIllegalTrajectory(const IllegalTrajectoryException & e);
void addLegalTrajectory();
std::map<std::pair<std::string, std::string>, double> getPercentages() const;
std::string getMessage() const;
-- protected data --
std::map<std::pair<std::string, std::string>, unsigned int> counts_;
unsigned int legal_count_, illegal_count_;
}

class DWBPublisher
{
-- public method --
explicit DWBPublisher(node, plugin_name);
nav2_util::CallbackReturn on_configure();
nav2_util::CallbackReturn on_activate();
nav2_util::CallbackReturn on_deactivate();
nav2_util::CallbackReturn on_cleanup();
bool shouldRecordEvaluation()
void publishEvaluation(results);
void publishLocalPlan(header,traj);
void publishCostGrid(costmap_ros,critics);
void publishGlobalPlan(const nav_2d_msgs::msg::Path2D plan);
void publishTransformedPlan(const nav_2d_msgs::msg::Path2D plan);
void publishLocalPlan(const nav_2d_msgs::msg::Path2D plan);
-- protected method --
void publishTrajectories(const dwb_msgs::msg::LocalPlanEvaluation & results);
void publishGenericPlan(plan,pub,flag);
bool publish_evaluation_;
bool publish_global_plan_;
bool publish_transformed_;
bool publish_local_plan_;
bool publish_trajectories_;
bool publish_cost_grid_pc_;
bool publish_input_params_;
builtin_interfaces::msg::Duration marker_lifetime_;
std::shared_ptr<LifecyclePublisher<dwb_msgs::msg::LocalPlanEvaluation>> eval_pub_;
std::shared_ptr<LifecyclePublisher<nav_msgs::msg::Path>> global_pub_;
std::shared_ptr<LifecyclePublisher<nav_msgs::msg::Path>> transformed_pub_;
std::shared_ptr<LifecyclePublisher<nav_msgs::msg::Path>> local_pub_;
std::shared_ptr<LifecyclePublisher<visualization_msgs::msg::MarkerArray>> marker_pub_;
std::shared_ptr<LifecyclePublisher<sensor_msgs::msg::PointCloud>> cost_grid_pc_pub_;
nav2_util::LifecycleNode::SharedPtr node_;
std::string plugin_name_;
}

class TrajectoryCritic
{
-- public method --
using Ptr = std::shared_ptr<dwb_core::TrajectoryCritic>;
virtual ~TrajectoryCritic() {}
void initialize(nh,name,ns,costmap_ros)
virtual void onInit()
virtual void reset() {}
virtual bool prepare(pose,twist,pose,plan)
virtual double scoreTrajectory(traj) = 0;
virtual void debrief(const nav_2d_msgs::msg::Twist2D &) {}
virtual void addCriticVisualization(sensor_msgs::msg::PointCloud &)
std::string getName()
virtual double getScale() const
void setScale(const double scale)
-- protected data --
std::string name_;
std::string dwb_plugin_name_;
std::shared_ptr<nav2_costmap_2d::Costmap2DROS> costmap_ros_;
double scale_;
nav2_util::LifecycleNode::SharedPtr nh_;
}

class TrajectoryGenerator{
-- public method --
typedef std::shared_ptr<dwb_core::TrajectoryGenerator> Ptr;
virtual ~TrajectoryGenerator()
virtual void initialize(nh,plugin_name) = 0;
virtual void reset()
virtual void startNewIteration(current_velocity) = 0;
virtual bool hasMoreTwists() = 0;
virtual nav_2d_msgs::msg::Twist2D nextTwist() = 0;
virtual std::vector<Twist2D> getTwists(current_velocity)
virtual Trajectory2D generateTrajectory(start_pose,start_vel,cmd_vel) = 0;
}

class traj_utils
{
const Pose2D & getClosestPose(trajectory,time_offset);
Pose2D projectPose(trajectory,time_offset);
}

TrajectoryCritic *-- Costmap2D
DWBLocalPlanner *-- Costmap2D
DWBLocalPlanner *-- DWBPublisher
DWBLocalPlanner *-- TrajectoryCritic
DWBLocalPlanner *-- TrajectoryGenerator
}

namespace dwb_critics{
class LineIterator{
-- public method --
LineIterator(int x0, int y0, int x1, int y1)
bool isValid() const
void advance()
int getX() const
int getY() const
int getX0() const
int getY0() const
int getX1() const
int getY1() const
-- private data --
int x0_;
int y0_;
int x1_;
int y1_;
int x_;
int y_;
int deltax_;
int deltay_;
int curpixel_;
int xinc1_, xinc2_, yinc1_, yinc2_;
int den_, num_, numadd_, numpixels_;
}
class alignment_util{
Pose2D getForwardPose(pose, distance);
}

class TwirlingCritic{
-- public method --
void onInit() override
double scoreTrajectory(traj) override
}

class RotateToGoalCritic{
-- public method --
void onInit() override;
void reset() override;
bool prepare(pose, vel, goal, global_plan) override;
double scoreTrajectory(traj) override;
virtual double scoreRotation(traj);

-- private data --
bool in_window_;
bool rotating_;
double goal_yaw_;
double xy_goal_tolerance_;
double xy_goal_tolerance_sq_;
double current_xy_speed_sq_, stopped_xy_velocity_sq_;
double slowing_factor_;
double lookahead_time_;
}

class PreferForwardCritic{
-- public method --
PreferForwardCritic()
void onInit() override;
double scoreTrajectory(traj) override;

-- private data --
double penalty_, strafe_x_, strafe_theta_, theta_scale_;
}

class BaseObstacleCritic{
-- public method --
void onInit() override;
double scoreTrajectory(traj) override;
void addCriticVisualization(pc) override;
virtual double scorePose(const geometry_msgs::msg::Pose2D & pose);
virtual bool isValidCost(const unsigned char cost);
-- protected data --
nav2_costmap_2d::Costmap2D * costmap_;
bool sum_scores_;
}

class ObstacleFootprintCritic{
-- public method --
Footprint getOrientedFootprint(pose,footprint_spec);
bool prepare(pose, vel, goal, global_plan) override;
double scorePose(pose) override;
virtual double scorePose(pose, oriented_footprint);
double getScale() const override
-- protected method --
double lineCost(int x0, int x1, int y0, int y1);
double pointCost(int x, int y);
-- protected data --
Footprint footprint_spec_;
}




class MapGridQueue{
-- public method --
MapGridQueue(nav2_costmap_2d::Costmap2D & costmap, MapGridCritic & parent)
virtual ~MapGridQueue() = default;
bool validCellToQueue(const costmap_queue::CellData & cell) override;
-- protected data --
MapGridCritic & parent_;
}
enum ScoreAggregationType{
Last,
Sum,
Product
}

class MapGridCritic{
-- public method --
void onInit() override;
double scoreTrajectory(const dwb_msgs::msg::Trajectory2D & traj) override;
void addCriticVisualization(sensor_msgs::msg::PointCloud & pc) override;
double getScale() const override
virtual double scorePose(const geometry_msgs::msg::Pose2D & pose);
inline double getScore(unsigned int x, unsigned int y)
void setAsObstacle(unsigned int index);
-- protected method --
void reset() override;
void propogateManhattanDistances();
-- protected data --
std::shared_ptr<MapGridQueue> queue_;
nav2_costmap_2d::Costmap2D * costmap_;
std::vector<double> cell_values_;
double obstacle_score_, unreachable_score_;
bool stop_on_failure_;
ScoreAggregationType aggregationType_;
}


class GoalDistCritic{
-- public method --
bool prepare(pose,vel,goal,global_plan) override;

-- protected method --
bool getLastPoseOnCostmap(global_plan, x,y);
}
class GoalAlignCritic{
-- public method --
GoalAlignCritic()
void onInit() override;
bool prepare(pose, vel, goal, global_plan) override;
double scorePose(const geometry_msgs::msg::Pose2D & pose) override;

-- protected data --
double forward_point_distance_;
}

class PathDistCritic{
-- public method --
bool prepare(pose, vel, goal, global_plan) override;
}

class PathAlignCritic{
-- public method --
PathAlignCritic()
void onInit() override;
bool prepare(pose, vel, goal, global_plan) override;
double getScale() const override;
double scorePose(const geometry_msgs::msg::Pose2D & pose) override;
-- protected data --
bool zero_scale_;
double forward_point_distance_;
}

class CommandTrend{
-- public method --
CommandTrend();
void reset();
bool update(double velocity);
bool isOscillating(double velocity);
bool hasSignFlipped();
-- private method --
enum class Sign { ZERO, POSITIVE, NEGATIVE };
Sign sign_;
bool positive_only_, negative_only_;
}

class OscillationCritic{
-- public method --
OscillationCritic()
void onInit() override;
bool prepare(pose, vel, goal, global_plan) override;
double scoreTrajectory(traj) override;
void reset() override;
void debrief(cmd_vel) override;
-- private method --
bool setOscillationFlags(const nav_2d_msgs::msg::Twist2D & cmd_vel);
bool resetAvailable();
-- private data --
CommandTrend x_trend_, y_trend_, theta_trend_;
double oscillation_reset_dist_, oscillation_reset_angle_, x_only_threshold_;
rclcpp::Duration oscillation_reset_time_;
double oscillation_reset_dist_sq_;
geometry_msgs::msg::Pose2D pose_, prev_stationary_pose_;
rclcpp::Time prev_reset_time_;
}

OscillationCritic *-- CommandTrend
BaseObstacleCritic <-- ObstacleFootprintCritic
BaseObstacleCritic *-- Costmap2D
MapGridCritic *-- Costmap2D
MapGridCritic *-- ScoreAggregationType
MapGridCritic *-- MapGridQueue
MapGridQueue *-- MapGridCritic
MapGridCritic <-- GoalDistCritic
GoalDistCritic <-- GoalAlignCritic
MapGridCritic <-- PathDistCritic
PathDistCritic <-- PathAlignCritic
}


dwb_core.TrajectoryCritic <-- dwb_critics.OscillationCritic
costmap_queue.CostmapQueue <-- dwb_critics.MapGridQueue
dwb_core.TrajectoryCritic <-- dwb_critics.MapGridCritic
dwb_core.TrajectoryCritic <-- dwb_critics.PreferForwardCritic
dwb_core.TrajectoryCritic <-- dwb_critics.RotateToGoalCritic
dwb_core.TrajectoryCritic <-- dwb_critics.TwirlingCritic
dwb_core.TrajectoryCritic <-- dwb_critics.BaseObstacleCritic

dwb_core.TrajectoryGenerator <-- dwb_plugins.StandardTrajectoryGenerator
nav2_core.Controller <-- dwb_core.DWBLocalPlanner




@enduml