@startuml
'https://plantuml.com/class-diagram
namespace nav2_core{
class GoalChecker{
-- public method --
typedef std::shared_ptr<nav2_core::GoalChecker> Ptr;
virtual ~GoalChecker()
virtual void initialize(nh,plugin_name) = 0;
virtual void reset() = 0;
virtual bool isGoalReached(query_pose,goal_pose,velocity) = 0;
}
}
@enduml