@startuml
'https://plantuml.com/class-diagram
namespace nav2_lifecycle_manager{
class LifecycleManager{
-- public method --
LifecycleManager();
~LifecycleManager();

-- protected method --
void managerCallback(request_header,request,response);
void isActiveCallback(request_header,request,response);

-- protected data --
rclcpp::Node::SharedPtr service_client_node_;
rclcpp::Service<ManageLifecycleNodes>::SharedPtr manager_srv_;
rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr is_active_srv_;

}

















rclcpp::Node <-- LifecycleManager

}

@enduml