@startuml
'https://plantuml.com/class-diagram

namespace nav2_costmap_2d{
class ArrayParser{
-- public method --
vector<vector<float>> parseVVF(input, error_return);
}
enum CostValues{
NO_INFORMATION = 255,
LETHAL_OBSTACLE = 254,
INSCRIBED_INFLATED_OBSTACLE = 253,
FREE_SPACE = 0
}
class CollisionCheckerException{
-- public method --
explicit CollisionCheckerException(const std::string description)
}
class IllegalPoseException
{
-- public method --
IllegalPoseException(const std::string name, const std::string description)
-- protected data --
std::string name_;
}
CollisionCheckerException <-- IllegalPoseException
class CostmapMath{
inline double sign(double x)
inline double sign0(double x)
inline double distance(double x0, double y0, double x1, double y1)
double distanceToLine(pX, pY, x0, y0, x1, y1);
bool intersects(std::vector<Point> & polygon, float testx, float testy);
bool intersects(polygon1, polygon2);
}
class footprint{
void calculateMinAndMaxDistances(footprint, min_dist, max_dist);
geometry_msgs::msg::Point toPoint(geometry_msgs::msg::Point32 pt);
geometry_msgs::msg::Point32 toPoint32(geometry_msgs::msg::Point pt);
geometry_msgs::msg::Polygon toPolygon(std::vector<geometry_msgs::msg::Point> pts);
std::vector<geometry_msgs::msg::Point> toPointVector(:Polygon::SharedPtr polygon);
void transformFootprint(x,y,theta,footprint_spec,oriented_footprint);
void transformFootprint(x,y,theta,footprint_spec,oriented_footprint);
void padFootprint(std::vector<geometry_msgs::msg::Point> & footprint, double padding);
std::vector<geometry_msgs::msg::Point> makeFootprintFromRadius(double radius);
bool makeFootprintFromString(footprint_string,footprint);
}
class FootprintSubscriber{
-- public method --
FootprintSubscriber(node, topic_name, footprint_timeout);
FootprintSubscriber(node, topic_name, footprint_timeout);
FootprintSubscriber(node_base, node_topics, node_logging, node_clock, topic_name, footprint_timeout);
~FootprintSubscriber() {}
bool getFootprint(footprint, valid_footprint_timeout);
bool getFootprint(std::vector<geometry_msgs::msg::Point> & footprint);
bool getFootprint(footprint, stamp,  valid_footprint_timeout);
-- protected method --
void footprint_callback(const geometry_msgs::msg::PolygonStamped::SharedPtr msg);
-- protected data --
rclcpp::node_interfaces::NodeBaseInterface::SharedPtr node_base_;
rclcpp::node_interfaces::NodeTopicsInterface::SharedPtr node_topics_;
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging_;
rclcpp::node_interfaces::NodeClockInterface::SharedPtr node_clock_;
void footprint_callback(const geometry_msgs::msg::PolygonStamped::SharedPtr msg);
std::string topic_name_;
bool footprint_received_{false};
rclcpp::Duration footprint_timeout_;
geometry_msgs::msg::PolygonStamped::SharedPtr footprint_;
rclcpp::Subscription<geometry_msgs::msg::PolygonStamped>::SharedPtr footprint_sub_;

}

class FootprintCollisionChecker<?CostmapT>{
-- public method --
FootprintCollisionChecker();
explicit FootprintCollisionChecker(CostmapT costmap);
double footprintCost(const Footprint footprint);
double footprintCostAtPose(double x, double y, double theta, const Footprint footprint);
double lineCost(int x0, int x1, int y0, int y1) const;
bool worldToMap(double wx, double wy, unsigned int & mx, unsigned int & my);
double pointCost(int x, int y) const;
void setCostmap(CostmapT costmap);

-- protected data --
CostmapT costmap_

}

class CostmapTopicCollisionChecker{
-- public method --
CostmapTopicCollisionChecker(costmap_sub,footprint_sub, tf, name, global_frame, robot_base_frame,transform_tolerance);
~CostmapTopicCollisionChecker()
double scorePose(const geometry_msgs::msg::Pose2D & pose);
bool isCollisionFree(const geometry_msgs::msg::Pose2D & pose);
-- protected method --
void unorientFootprint(const Footprint & oriented_footprint, Footprint & reset_footprint);
Footprint getFootprint(const geometry_msgs::msg::Pose2D & pose);
-- protected data --
std::string name_;
std::string global_frame_;
std::string robot_base_frame_;
tf2_ros::Buffer & tf_;
CostmapSubscriber & costmap_sub_;
FootprintSubscriber & footprint_sub_;
double transform_tolerance_;
FootprintCollisionChecker<std::shared_ptr<Costmap2D>> collision_checker_;
}
CostmapTopicCollisionChecker *-- CostmapSubscriber
CostmapTopicCollisionChecker *-- FootprintSubscriber
CostmapTopicCollisionChecker *-- FootprintCollisionChecker

class Costmap{

}
class MapLocation{
unsigned int x
unsigned int y
}
class MarkCell{
-- public method --
MarkCell(unsigned char * costmap, unsigned char value)
inline void operator()(unsigned int offset)
-- private data --
unsigned char * costmap_;
unsigned char value_;
}
class PolygonOutlineCells{
-- public: method --
PolygonOutlineCells(
inline void operator()(unsigned int offset)
-- private data --
const Costmap2D & costmap_;
std::vector<MapLocation> & cells_;
}

PolygonOutlineCells *-- Costmap2D
PolygonOutlineCells *-- MapLocation


class Costmap2D{
-- public method --
Costmap2D();
virtual ~Costmap2D();
unsigned char getCost(unsigned int mx, unsigned int my) const;
unsigned char getCost(unsigned int index) const;
void setCost(unsigned int mx, unsigned int my, unsigned char cost);
void mapToWorld(unsigned int mx, unsigned int my, double & wx, double & wy) const;
bool worldToMap(double wx, double wy, unsigned int & mx, unsigned int & my) const;
void worldToMapNoBounds(double wx, double wy, int & mx, int & my) const;
void worldToMapEnforceBounds(double wx, double wy, int & mx, int & my) const;
inline unsigned int getIndex(unsigned int mx, unsigned int my) const
inline void indexToCells(unsigned int index, unsigned int & mx, unsigned int & my) const
unsigned char * getCharMap() const;
unsigned int getSizeInCellsX() const;
unsigned int getSizeInCellsY() const;
double getSizeInMetersX() const;
double getSizeInMetersY() const;
double getOriginX() const;
double getOriginY() const;
double getResolution() const;
void setDefaultValue(unsigned char c)
unsigned char getDefaultValue()
bool setConvexPolygonCost()
void polygonOutlineCells()
void convexFillCells()
virtual void updateOrigin(double new_origin_x, double new_origin_y);
bool saveMap(std::string file_name);
void resizeMap()
void resetMap(unsigned int x0, unsigned int y0, unsigned int xn, unsigned int yn);
void resetMapToValue()
unsigned int cellDistance(double world_dist);
typedef std::recursive_mutex mutex_t;
mutex_t * getMutex()
-- protected method --
void copyMapRegion()
virtual void deleteMaps();
virtual void resetMaps();
virtual void initMaps(unsigned int size_x, unsigned int size_y);
inline void raytraceLine(at, x0, y0, x1, y1, max_length)

-- protected data --
unsigned int size_x_;
unsigned int size_y_;
double resolution_;
double origin_x_;
double origin_y_;
unsigned char * costmap_;
unsigned char default_value_;

-- private method --
inline void bresenham2D(at,abs_da,abs_db,error_b,offset_a,offset_b,offset,max_length)
-- private data --
mutex_t * access_;
}
Costmap2D *-- PolygonOutlineCells
Costmap2D *-- MarkCell
class Costmap2DROS{
-- public method --
explicit Costmap2DROS(const std::string & name);
explicit Costmap2DROS(name,parent_namespace, local_namespace);
~Costmap2DROS();
nav2_util::CallbackReturn on_configure(const rclcpp_lifecycle::State & state) override;
nav2_util::CallbackReturn on_activate(const rclcpp_lifecycle::State & state) override;
nav2_util::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & state) override;
nav2_util::CallbackReturn on_cleanup(const rclcpp_lifecycle::State & state) override;
nav2_util::CallbackReturn on_shutdown(const rclcpp_lifecycle::State & state) override;
void start();
void stop();
void pause();
void resume();
void updateMap();
void resetLayers();
bool isCurrent()
bool getRobotPose(geometry_msgs::msg::PoseStamped & global_pose);
std::string getName() const
double getTransformTolerance() const
Costmap2D * getCostmap()
std::string getGlobalFrameID()
std::string getBaseFrameID()
LayeredCostmap * getLayeredCostmap()
geometry_msgs::msg::Polygon getRobotFootprintPolygon()
std::vector<geometry_msgs::msg::Point> getRobotFootprint()
std::vector<geometry_msgs::msg::Point> getUnpaddedRobotFootprint()
void getOrientedFootprint(std::vector<geometry_msgs::msg::Point> & oriented_footprint);
void setRobotFootprint(const std::vector<geometry_msgs::msg::Point> & points);
void setRobotFootprintPolygon(const geometry_msgs::msg::Polygon::SharedPtr footprint);
std::shared_ptr<tf2_ros::Buffer> getTfBuffer() {return tf_buffer_;}
bool getUseRadius() {return use_radius_;}
-- protected method --
void getParameters();
-- protected data --
rclcpp::Node::SharedPtr client_node_;
LifecyclePublisher<PolygonStamped>   footprint_pub_;
Costmap2DPublisher * costmap_publisher_{nullptr};
Subscription<Polygon>::SharedPtr footprint_sub_;
Subscription<ParameterEvent>::SharedPtr parameter_sub_;
std::shared_ptr<tf2_ros::Buffer> tf_buffer_;
std::shared_ptr<tf2_ros::TransformListener> tf_listener_;
LayeredCostmap * layered_costmap_{nullptr};
std::string name_;
std::string parent_namespace_;
void mapUpdateLoop(double frequency);
bool map_update_thread_shutdown_{false};
bool stop_updates_{false};
bool initialized_{false};
bool stopped_{true};
std::thread * map_update_thread_
rclcpp::Time last_publish_{0, 0, RCL_ROS_TIME};
rclcpp::Duration publish_cycle_{1, 0};
pluginlib::ClassLoader<Layer> plugin_loader_
bool always_send_full_costmap_{false};
std::string footprint_;
float footprint_padding_{0};
std::string global_frame_;
int map_height_meters_{0};
double map_publish_frequency_{0};
double map_update_frequency_{0};
int map_width_meters_{0};
double origin_x_{0};
double origin_y_{0};
std::vector<std::string> default_plugins_;
std::vector<std::string> default_types_;
std::vector<std::string> plugin_names_;
std::vector<std::string> plugin_types_;
double resolution_{0};
std::string robot_base_frame_;
double robot_radius_;
bool rolling_window_{false};
bool track_unknown_space_{false};
double transform_tolerance_{0};
bool use_radius_{false};
std::vector<geometry_msgs::msg::Point> unpadded_footprint_;
std::vector<geometry_msgs::msg::Point> padded_footprint_;
std::unique_ptr<ClearCostmapService> clear_costmap_service_;
}
LifecycleNode <-- Costmap2DROS
Costmap2DROS *-- Costmap2DPublisher
Costmap2DROS *-- LayeredCostmap
Costmap2DROS *-- ClearCostmapService

class LayeredCostmap{
-- public method --
LayeredCostmap(std::string global_frame, bool rolling_window, bool track_unknown);
~LayeredCostmap();
void updateMap(double robot_x, double robot_y, double robot_yaw);
std::string getGlobalFrameID() const
void resizeMap(size_x, size_y, resolution, origin_x,origin_y, size_locked);
void getUpdatedBounds(double & minx, double & miny, double & maxx, double & maxy)
bool isCurrent();
Costmap2D * getCostmap()
bool isRolling()
bool isTrackingUnknown()
std::vector<std::shared_ptr<Layer>> * getPlugins()
void addPlugin(std::shared_ptr<Layer> plugin)
bool isSizeLocked()
void getBounds(unsigned int * x0, unsigned int * xn, unsigned int * y0, unsigned int * yn)
bool isInitialized()
void setFootprint(const std::vector<geometry_msgs::msg::Point> & footprint_spec);
const std::vector<geometry_msgs::msg::Point> & getFootprint() {return footprint_;}
double getCircumscribedRadius() {return circumscribed_radius_;}
double getInscribedRadius() {return inscribed_radius_;}
bool isOutofBounds(double robot_x, double robot_y);
-- private data --
Costmap2D costmap_;
std::string global_frame_;
bool rolling_window_;
bool current_;
double minx_, miny_, maxx_, maxy_;
unsigned int bx0_, bxn_, by0_, byn_;
std::vector<std::shared_ptr<Layer>> plugins_;
bool initialized_;
bool size_locked_;
double circumscribed_radius_, inscribed_radius_;
std::vector<geometry_msgs::msg::Point> footprint_;
}
LayeredCostmap *-- Costmap2D
LayeredCostmap o-- Layer

class Layer{
-- public method --
Layer();
virtual ~Layer() {}
void initialize(parent, name, tf, node, client_node, rclcpp_node);
virtual void deactivate()
virtual void activate()
virtual void reset()
virtual void updateBounds(robot_x,robot_y,robot_yaw,min_x,min_y,max_x,max_y);
virtual void updateCosts(master_grid,min_i,min_j,max_i,max_j) = 0;
virtual void matchSize() {}
virtual void onFootprintChanged() {}
std::string getName() const
bool isCurrent() const
const std::vector<geometry_msgs::msg::Point> & getFootprint() const;
void declareParameter(const std::string & param_name, const rclcpp::ParameterValue & value);
bool hasParameter(const std::string & param_name);
void undeclareAllParameters();
std::string getFullName(const std::string & param_name);
-- protected method --
virtual void onInitialize() {}

-- protected data --
LayeredCostmap * layered_costmap_;
std::string name_;
tf2_ros::Buffer * tf_;
nav2_util::LifecycleNode::SharedPtr node_;
rclcpp::Node::SharedPtr client_node_;
rclcpp::Node::SharedPtr rclcpp_node_;
bool current_;
bool enabled_;
std::unordered_set<std::string> local_params_;
-- private data --
std::vector<geometry_msgs::msg::Point> footprint_spec_;
}
Layer *-- LayeredCostmap

class CostmapLayer{
-- public method --
CostmapLayer()
bool isDiscretized()
virtual void matchSize();
virtual void clearArea(int start_x, int start_y, int end_x, int end_y);
void addExtraBounds(double mx0, double my0, double mx1, double my1);
-- protected method --
void updateWithTrueOverwrite();
void updateWithOverwrite();
void updateWithMax();
void updateWithAddition();
void touch();
void useExtraBounds(double * min_x, double * min_y, double * max_x, double * max_y);
-- protected data --
bool has_extra_bounds_;
-- private data --
double extra_min_x_, extra_max_x_, extra_min_y_, extra_max_y_;
}

Layer <-- CostmapLayer
Costmap2D <-- CostmapLayer

class StaticLayer{
-- public method --
StaticLayer();
virtual ~StaticLayer();
virtual void onInitialize();
virtual void activate();
virtual void deactivate();
virtual void reset();
virtual void updateBounds();
virtual void updateCosts();
virtual void matchSize();
-- private method --
void getParameters();
void processMap(const nav_msgs::msg::OccupancyGrid & new_map);
void incomingMap(const nav_msgs::msg::OccupancyGrid::SharedPtr new_map);
void incomingUpdate(map_msgs::msg::OccupancyGridUpdate::ConstSharedPtr update);
unsigned char interpretValue(unsigned char value);
-- private data --
std::string global_frame_;
std::string map_frame_;
bool has_updated_data_{false};
unsigned int x_{0};
unsigned int y_{0};
unsigned int width_{0};
unsigned int height_{0};
Subscription<:OccupancyGrid> map_sub_;
Subscription<OccupancyGridUpdate> map_update_sub_;
std::string map_topic_;
bool map_subscribe_transient_local_;
bool subscribe_to_updates_;
bool track_unknown_space_;
bool use_maximum_;
unsigned char lethal_threshold_;
unsigned char unknown_cost_value_;
bool trinary_costmap_;
bool map_received_{false};
tf2::Duration transform_tolerance_;
std::atomic<bool> update_in_progress_;
nav_msgs::msg::OccupancyGrid::SharedPtr map_buffer_;
}
CostmapLayer <-- StaticLayer
enum InputSensorType{
VARIABLE,
FIXED,
ALL
}
class RangeSensorLayer{
-- public method --
virtual void onInitialize();
virtual void updateBounds();
virtual void updateCosts();
virtual void reset();
virtual void deactivate();
virtual void activate();
void bufferIncomingRangeMsg()
-- private method --
void updateCostmap();
void processRangeMsg(Range & range_message);
void processFixedRangeMsg(Range & range_message);
void processVariableRangeMsg(Range & range_message);
void resetRange();
inline double gamma(double theta);
inline double delta(double phi);
inline double sensor_model(double r, double phi, double theta);
inline void get_deltas(double angle, double * dx, double * dy);
inline void update_cell(ox, oy, ot, r, nx, ny, clear);
inline double to_prob(unsigned char c)
inline unsigned char to_cost(double p)
float area(int x1, int y1, int x2, int y2, int x3, int y3)
int orient2d(int Ax, int Ay, int Bx, int By, int Cx, int Cy)
-- private data --
std::function<void(Range & range_message)> processRangeMessageFunc_;
std::mutex range_message_mutex_;
std::list<Range> range_msgs_buffer_;
double max_angle_, phi_v_;
double inflate_cone_;
std::string global_frame_;
double clear_threshold_, mark_threshold_;
bool clear_on_max_reading_;
tf2::Duration transform_tolerance_;
double no_readings_timeout_;
rclcpp::Time last_reading_time_;
unsigned int buffered_readings_;
std::vector<Subscription<Range>::SharedPtr> range_subs_;
double min_x_, min_y_, max_x_, max_y_;
}
CostmapLayer <-- RangeSensorLayer

Class CostmapSubscriber{
-- public method --
CostmapSubscriber(node, topic_name);
CostmapSubscriber(node, topic_name);
CostmapSubscriber(node_base, node_topics, node_logging, topic_name);
~CostmapSubscriber()
std::shared_ptr<Costmap2D> getCostmap();
-- protected method --
void toCostmap2D();
void costmapCallback(const nav2_msgs::msg::Costmap::SharedPtr msg);
-- protected data --
rclcpp::node_interfaces::NodeBaseInterface::SharedPtr node_base_;
rclcpp::node_interfaces::NodeTopicsInterface::SharedPtr node_topics_;
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging_;
std::shared_ptr<Costmap2D> costmap_;
nav2_msgs::msg::Costmap::SharedPtr costmap_msg_;
std::string topic_name_;
bool costmap_received_{false};
rclcpp::Subscription<nav2_msgs::msg::Costmap>::SharedPtr costmap_sub_;
}
CostmapSubscriber *-- Costmap

class ClearCostmapService{
-- public method --
ClearCostmapService(node, costmap);
ClearCostmapService() = delete;
void clearExceptRegion(double reset_distance);
void clearAroundRobot( window_size_x, window_size_y);
void clearEntirely();

-- private method --
void clearExceptRegionCallback(request_header, request, response);
void clearAroundRobotCallback(request_header, request, response);
void clearEntireCallback(request_header, request, response);
void clearLayerExceptRegion(costmap, pose_x, pose_y, reset_distance);
bool isClearable(const std::string & layer_name) const;
bool getPosition(double & x, double & y) const;
std::string getLayerName(const Layer & layer) const;
-- private data --
nav2_util::LifecycleNode::SharedPtr node_;
Costmap2DROS & costmap_;
unsigned char reset_value_;
std::vector<std::string> clearable_layers_;
Service<ClearCostmapExceptRegion> clear_except_service_;
Service<ClearCostmapAroundRobot>::SharedPtr clear_around_service_;
Service<ClearEntireCostmap>::SharedPtr clear_entire_service_;
}

class Costmap2DPublisher{
-- public method --
Costmap2DPublisher(ros_node,costmap,global_frame,topic_name,always_send_full_costmap);
~Costmap2DPublisher();
void on_configure()
void on_activate()
void on_deactivate()
void on_cleanup() {}
void updateBounds(x0,xn,y0,yn)
void publishCostmap();
bool active()
-- private method --
void prepareGrid();
void prepareCostmap();
void costmap_service_callback( request_header, request, response);
-- private data --
nav2_util::LifecycleNode::SharedPtr node_;
Costmap2D * costmap_;
std::string global_frame_;
std::string topic_name_;
unsigned int x0_, xn_, y0_, yn_;
double saved_origin_x_;
double saved_origin_y_;
bool active_;
bool always_send_full_costmap_;
LifecyclePublisher<OccupancyGrid>::SharedPtr costmap_pub_;
LifecyclePublisher<OccupancyGridUpdate> costmap_update_pub_;
LifecyclePublisher<Costmap>::SharedPtr costmap_raw_pub_;
Service<GetCostmap>::SharedPtr costmap_service_;
float grid_resolution;
unsigned int grid_width, grid_height;
std::unique_ptr<nav_msgs::msg::OccupancyGrid> grid_;
std::unique_ptr<nav2_msgs::msg::Costmap> costmap_raw_;
static char * cost_translation_table_;
}

ClearCostmapService *-- Costmap2DROS
Costmap2DPublisher *-- Costmap2D
Costmap2DPublisher *-- Costmap
}
std.runtime_error <-- nav2_costmap_2d.CollisionCheckerException
@enduml