@startuml
'https://plantuml.com/class-diagram

namespace nav2_util{
class NodeThread{
-- public method --
explicit NodeThread(node_base);
template<typename NodeT>
explicit NodeThread(NodeT node)
~NodeThread();
-- protected data --
rclcpp::node_interfaces::NodeBaseInterface::SharedPtr node_;
std::unique_ptr<std::thread> thread_;
rclcpp::executors::SingleThreadedExecutor executor_;

}
}
@enduml