@startuml
'https://plantuml.com/class-diagram

namespace nav2_util{
class StringUtils{
-- public method --
typedef std::vector<std::string> Tokens;
std::string strip_leading_slash(const std::string & in);
Tokens split(const std::string & tokenstring, char delimiter);
}
}
@enduml